import argparse


parse = argparse.ArgumentParser()
parse.add_argument('--train',type=int,default=1)
parse.add_argument('--log',type=int,default=0)
parse.add_argument('--model',type=str,default='HSRNet')
parse.add_argument('--dataset',type=str,default='PaviaU')
parse.add_argument('--task',type=str,default='hsi_msi_fusion')
parse.add_argument('--check_point', type=str, default=None)
parse.add_argument('--batch_size',type=int,default=8)
parse.add_argument('--epochs',type=int,default=300)
parse.add_argument('--seed',type=int,default=3407)
parse.add_argument('--upscale',type=int,default=4) 
parse.add_argument('--patch_size',type=int,default=64) 
parse.add_argument('--msi_bands',type=int,default=4) 
parse.add_argument('--dim',type=int,default=64) 
parse.add_argument('--val_step',type=int,default=1) 
parse.add_argument('--save_step',type=int,default=50)
parse.add_argument('--device',type=str,default='cuda:0') 
parse.add_argument('--is_train',type=int,default=1) 
parse.add_argument('--param_table',type=int,default=0)
parse.add_argument('--lr',type=float, default=4e-4)
parse.add_argument('--loss_func',type=str,default='L1Loss')
parse.add_argument('--optimizer',type=str,default='Adam')
parse.add_argument('--lr_decay_step',type=int,default=200)
parse.add_argument('--decay',type=float,default=0.1)
parse.add_argument('--data_size',type=int,default=-1)
args = parse.parse_args()

